{
 "title": "Launch",
 "panels": [
  {
   "title": "LaunchGroups [1m]",
   "type": "graph",
   "targets": [
    {
     "expr": "rate(operation_launch_group[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LaunchGroups [1m] (stacked)",
   "type": "graph",
   "targets": [
    {
     "expr": "rate(operation_launch_group[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}
{
 "title": "Offers",
 "panels": [
  {
   "title": "Processed Offers",
   "type": "graph",
   "targets": [
    { "expr": "rate(offers_processed[1m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Processed Offers [1m] (stacked)",
   "type": "graph",
   "targets": [
    { "expr": "rate(offers_processed[1m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Received Offers [1m]",
   "type": "graph",
   "targets": [
    { "expr": "rate(offers_received[1m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Received Offers [1m] (stacked)",
   "type": "graph",
   "targets": [
    { "expr": "rate(offers_received[1m])", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}
{
 "title": "Decline / Revive",
 "panels": [
  {
   "title": "Revives [1m]",
   "type": "graph",
   "targets": [
    { "expr": "rate(revives[1m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Short Declines [1m]",
   "type": "graph",
   "targets": [
    {
     "expr": "rate(mesos_scheduler_decline_short_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Long Declines [1m]",
   "type": "graph",
   "targets": [
    { "expr": "rate(declines_long[1m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Revives (cumulative)",
   "type": "graph",
   "targets": [
    { "expr": "revives", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Short Declines [1m] (stacked)",
   "type": "graph",
   "targets": [
    {
     "expr": "rate(mesos_scheduler_decline_short_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Long Declines [1m] (cumulative)",
   "type": "graph",
   "targets": [
    { "expr": "rate(declines_long[1m])", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "ProcessOffers Median",
   "type": "graph",
   "targets": [
    {
     "expr": "offers_process{quantile=\"0.5\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}
{
 "title": "Jenkins",
 "panels": [
  {
   "title": "Provision Submit",
   "type": "graph",
   "description": "Time taken from .submit call to request being satisfied.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(mesos_cloud_nolabel_provision_submit)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Launch Time",
   "type": "graph",
   "description": "Time spent in Mesos Computer launch call",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(mesos_computer_launcher_launch)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}