{
 "title": "Jenkins: Mesos",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Launch Rate [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "launches/s" }
   ],
   "targets": [
    {
     "expr": "rate(mesos_scheduler_operation_launch[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Launch Rate [1m] (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "launches/s" }
   ],
   "targets": [
    {
     "expr": "rate(mesos_scheduler_operation_launch[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Processed Offers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "offers/s" }
   ],
   "targets": [
    {
     "expr": "rate(mesos_scheduler_offer_processing_time_count[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Processed Offers [1m] (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "offers/s" }
   ],
   "targets": [
    {
     "expr": "rate(mesos_scheduler_offer_processing_time_count[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Received Offers [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "offers/s" }
   ],
   "targets": [
    {
     "expr": "rate(mesos_scheduler_offers_received_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Received Offers [1m] (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "offers/s" }
   ],
   "targets": [
    {
     "expr": "rate(mesos_scheduler_offers_received_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Revives [1m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "revives/s" }
   ],
   "targets": [
    {
     "expr": "rate(mesos_scheduler_revives_count[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Short Declines [1m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "declines/s" }
   ],
   "targets": [
    {
     "expr": "rate(mesos_scheduler_decline_short_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Long Declines [1m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "declines/s" }
   ],
   "targets": [
    {
     "expr": "rate(mesos_scheduler_decline_long_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Revives (cumulative)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "revives/s" }
   ],
   "targets": [
    { "expr": "mesos_scheduler_revives_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Short Declines [1m] (stacked)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "declines/s" }
   ],
   "targets": [
    {
     "expr": "rate(mesos_scheduler_decline_short_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Long Declines [1m] (cumulative)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "declines/s" }
   ],
   "targets": [
    {
     "expr": "rate(mesos_scheduler_decline_long_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ProcessOffers Median",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "mesos_scheduler_offer_processing_time{quantile=\"0.5\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Provision Submit",
   "type": "graph",
   "description": "Time taken from .submit call to request being satisfied.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(mesos_cloud_nolabel_provision_submit)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Launch Time",
   "type": "graph",
   "description": "Time spent in Mesos Computer launch call",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(mesos_computer_launcher_launch)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}