{
 "title": "Jenkins: Jobs",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Queue Size (stacked)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_queue_size_value", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Success Rate [1m]",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "runs/second" }
   ],
   "targets": [
    {
     "expr": "rate(jenkins_runs_success_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Success Rate [1m] (stacked)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "runs/second" }
   ],
   "targets": [
    {
     "expr": "rate(jenkins_runs_success_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Executors Free (stacked)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Executors" }
   ],
   "targets": [
    { "expr": "jenkins_executor_free_value", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Failure Rate [1m]",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jenkins_runs_failure_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failure Rate [1m] (stacked)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "runs/second" }
   ],
   "targets": [
    {
     "expr": "rate(jenkins_runs_failure_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Executors Total (stacked)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Executors" }
   ],
   "targets": [
    { "expr": "jenkins_executor_count_value", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Build Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jenkins_runs_total_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Build Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jenkins_runs_total_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Job Waiting Duration (median)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_job_waiting_duration{quantile=\"0.5\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}